"""
WealthPath AI — Multi-Agent Workflow
-------------------------------------
7 specialized agents orchestrated sequentially:
  JUDGE (Perceive): Profile → Spending → Cashflow
  ACT   (Act):      Goal → Product → Report
  VERIFY (Verify):  RiskGuard

Each agent accepts structured input and returns a typed dict (Structured Output).
In production, LLM calls use JSON Schema / Structured Output to prevent hallucination.
Numeric calculations are handled by TypeScript-equivalent Python Tool functions —
the LLM only generates natural-language explanations, never raw numbers.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any
import json


# ─── Shared data models ───────────────────────────────────────────────────────

@dataclass
class UserProfile:
    age: int
    monthly_income: int          # KRW
    current_assets: int          # KRW
    monthly_fixed_expense: int   # KRW
    goals: list[str]
    retirement_age: int = 63
    expected_pension: int = 0    # KRW / month


@dataclass
class Transaction:
    category: str
    amount: int   # KRW


# ─── Tool functions (numeric computation — NOT generated by LLM) ─────────────

def _calc_months_to_goal(target: int, current: int, monthly_saving: int) -> int:
    """Calculate months needed to reach target amount."""
    if monthly_saving <= 0:
        return 999
    gap = max(target - current, 0)
    return max(1, round(gap / monthly_saving))


def _calc_retirement_cashflow(
    monthly_pension: int,
    financial_assets: int,
    monthly_living: int,
    monthly_medical: int,
    drawdown_years: int = 25,
) -> dict:
    """
    Estimate post-retirement monthly cashflow.
    Asset drawdown assumes equal monthly distribution over drawdown_years.
    """
    asset_monthly = financial_assets // (drawdown_years * 12)
    monthly_income = monthly_pension + asset_monthly
    monthly_expense = monthly_living + monthly_medical
    shortage = monthly_income - monthly_expense
    return {
        "monthly_income": monthly_income,
        "monthly_expense": monthly_expense,
        "monthly_shortage": shortage,                  # negative = deficit
        "30yr_cumulative_shortage": abs(min(shortage, 0)) * 12 * 30,
        "risk_level": "위험" if shortage < -600000 else
                      "주의" if shortage < 0 else "양호",
    }


def _physical_equivalent(amount_krw: int) -> str:
    """Map a savings amount to a relatable real-world equivalent."""
    if amount_krw >= 30_000_000:
        return "중형 SUV 1대"
    if amount_krw >= 10_000_000:
        return "비상금 목표 달성"
    if amount_krw >= 4_500_000:
        return "월세 3개월치"
    if amount_krw >= 2_280_000:
        return "국내 여행 숙박비 (제주 2박)"
    if amount_krw >= 1_000_000:
        return "최신 스마트폰 구입"
    return f"커피 {amount_krw // 5000}잔"


# ─── Agent definitions ────────────────────────────────────────────────────────

class ProfileAgent:
    """
    JUDGE — Perceive
    Classifies the user's life stage and financial priority based on their profile.
    Output is a Structured JSON used as input by downstream agents.
    """

    LIFE_STAGES = {
        "seed":        (19, 30),
        "asset_build": (30, 45),
        "retirement_prep": (45, 60),
        "retirement":  (60, 99),
    }

    def run(self, profile: UserProfile) -> dict:
        stage = next(
            (k for k, (lo, hi) in self.LIFE_STAGES.items()
             if lo <= profile.age < hi),
            "seed",
        )
        risk = (
            "high"   if profile.age < 35 else
            "medium" if profile.age < 50 else
            "low"
        )
        priority = (
            "비상금 확보 → 고정저축률 설정" if stage == "seed" else
            "자산형성 + 연금 시작"        if stage == "asset_build" else
            "은퇴 현금흐름 점검"           if stage == "retirement_prep" else
            "현금흐름 관리 + 금융보호"
        )
        return {
            "agent": "ProfileAgent",
            "life_stage": stage,
            "risk_capacity": risk,
            "priority": priority,
            "mode": "early_career" if stage in ("seed", "asset_build") else "retirement",
        }


class SpendingAgent:
    """
    JUDGE — Perceive
    Categorises transactions and flags over-spending items.
    """

    THRESHOLDS = {
        "배달": 0.10,   # >10% of income → warning
        "카페": 0.05,
        "구독": 0.03,
        "쇼핑": 0.15,
    }

    def run(self, transactions: list[Transaction], monthly_income: int) -> dict:
        category_totals: dict[str, int] = {}
        for tx in transactions:
            category_totals[tx.category] = category_totals.get(tx.category, 0) + tx.amount

        total = sum(category_totals.values())
        warnings = [
            cat for cat, amt in category_totals.items()
            if self.THRESHOLDS.get(cat, 1.0) < amt / max(monthly_income, 1)
        ]

        return {
            "agent": "SpendingAgent",
            "monthly_spending": total,
            "category_breakdown": category_totals,
            "overspend_warnings": warnings,
            "savings_capacity": max(monthly_income - total, 0),
        }


class CashflowAgent:
    """
    JUDGE — Perceive
    Calculates retirement cashflow and identifies monthly deficit.
    Delegates all numeric computation to _calc_retirement_cashflow() Tool.
    """

    def run(self, profile: UserProfile, monthly_medical: int = 250_000) -> dict:
        result = _calc_retirement_cashflow(
            monthly_pension=profile.expected_pension,
            financial_assets=profile.current_assets,
            monthly_living=profile.monthly_fixed_expense,
            monthly_medical=monthly_medical,
        )
        return {"agent": "CashflowAgent", **result}


class GoalAgent:
    """
    ACT — Act
    Generates Range-type saving nudges and calculates goal timeline scenarios.
    Uses _calc_months_to_goal() and _physical_equivalent() Tools — not LLM maths.
    """

    def run(
        self,
        profile: UserProfile,
        spending: dict,
        target_amount: int = 10_000_000,
    ) -> dict:
        base_saving = spending["savings_capacity"]

        scenarios = {}
        for label, extra in [
            ("현재 속도 (절약 없음)", 0),
            ("배달 주 1회↓ (월 +4만)", 40_000),
            ("배달 주 2회↓ (월 +8만)", 80_000),
            ("배달 2회 + 카페·구독 정리 (월 +15만)", 150_000),
        ]:
            months = _calc_months_to_goal(
                target_amount, profile.current_assets, base_saving + extra
            )
            scenarios[label] = months

        best_months = min(scenarios.values())
        six_month_savings = (base_saving + 40_000) * 6
        physical = _physical_equivalent(six_month_savings)

        return {
            "agent": "GoalAgent",
            "goal_amount": target_amount,
            "scenarios": scenarios,
            "best_case_months": best_months,
            "range_nudge": "배달 주문을 주 1~2회 줄이면 월 4~8만원 절약 가능",
            "physical_equivalent_6m": physical,
        }


class ProductAgent:
    """
    ACT — Act
    Maps life stage to appropriate JB Financial product groups on a 2×2 matrix
    (stability × liquidity). Does NOT recommend specific products — comparison only.
    """

    PRODUCT_MAP = {
        "seed": [
            {"name": "목돈만들기상품",   "stability": "높음", "liquidity": "중",  "suitability": "1순위", "note": "단기 목표 적합, 유동성 유지"},
            {"name": "ISA 계좌",        "stability": "중",   "liquidity": "중",  "suitability": "2순위", "note": "비과세 혜택, 3년 이상 권장"},
            {"name": "정기적금",         "stability": "높음", "liquidity": "낮음","suitability": "3순위", "note": "확정 금리, 중도 해지 불리"},
            {"name": "입출금자유예금",    "stability": "높음", "liquidity": "높음","suitability": "보조",  "note": "파킹용, 즉시 출금 가능"},
        ],
        "retirement_prep": [
            {"name": "퇴직연금 정기예금", "stability": "높음", "liquidity": "낮음","suitability": "1순위", "note": "연금 세제 혜택"},
            {"name": "연금보험",          "stability": "높음", "liquidity": "낮음","suitability": "2순위", "note": "월 현금흐름 보완"},
            {"name": "목돈굴리기상품",    "stability": "높음", "liquidity": "중",  "suitability": "3순위", "note": "거치식, 안정 수익"},
            {"name": "건강보험",          "stability": "높음", "liquidity": "낮음","suitability": "보조",  "note": "의료비 리스크 대비"},
        ],
    }

    def run(self, profile_result: dict) -> dict:
        stage = profile_result.get("life_stage", "seed")
        key = "retirement_prep" if stage in ("retirement_prep", "retirement") else "seed"
        products = self.PRODUCT_MAP[key]
        return {
            "agent": "ProductAgent",
            "matrix_axis_x": "유동성 (낮음 ↔ 높음)",
            "matrix_axis_y": "안정성 (낮음 ↔ 높음)",
            "products": products,
            "disclaimer": "상품군 비교·설명 목적이며 가입 권유가 아닙니다. 최종 가입 전 상품설명서를 확인하세요.",
        }


class RiskGuardAgent:
    """
    VERIFY — Verify
    Scans all agent outputs for compliance violations before rendering.
    Acts as a Compliance-aware Guardrail layer.
    """

    FORBIDDEN_PHRASES = [
        "수익률 보장", "원금 보장", "확실히 오릅니다", "반드시",
        "guaranteed return", "certain profit",
    ]

    def run(self, all_results: list[dict], explanation_text: str = "") -> dict:
        violations = []

        # Check for individual stock recommendations
        for r in all_results:
            if r.get("agent") == "ProductAgent":
                for p in r.get("products", []):
                    if any(kw in p["name"] for kw in ["삼성", "카카오", "KOSPI", "ETF 직접"]):
                        violations.append(f"개별 종목 추천 감지: {p['name']}")

        # Check explanation text for forbidden phrases
        for phrase in self.FORBIDDEN_PHRASES:
            if phrase in explanation_text:
                violations.append(f"금지 표현 감지: '{phrase}'")

        passed = len(violations) == 0
        return {
            "agent": "RiskGuardAgent",
            "passed": passed,
            "violations": violations,
            "checks_performed": [
                "개별 종목 추천 없음",
                "수익률 보장 표현 없음",
                "과도한 투자권유 없음",
                "환각·최신성 리스크 점검",
                "설명가능성 확인",
            ],
            "note": "수치는 DB/Tool에서, LLM은 설명만 — 환각 방지 적용",
        }


class ReportAgent:
    """
    ACT — Act (final)
    Assembles all structured agent outputs into a Wealth Report.
    LLM is called only for natural-language summary — numbers come from upstream agents.
    """

    def run(
        self,
        profile: dict,
        spending: dict,
        goal: dict,
        products: dict,
        risk_guard: dict,
        cashflow: dict | None = None,
    ) -> dict:
        mode = profile.get("mode", "early_career")

        if mode == "early_career":
            summary = (
                f"[생애 첫 자산관리 리포트]\n\n"
                f"생애단계: {profile['life_stage']} | 우선순위: {profile['priority']}\n"
                f"이번 달 지출: {spending['monthly_spending']:,}원\n"
                f"과소비 항목: {', '.join(spending['overspend_warnings']) or '없음'}\n\n"
                f"절약 넛지: {goal['range_nudge']}\n"
                f"목표 달성 최단 기간: {goal['best_case_months']}개월\n"
                f"6개월 절약 시 실물 환산: {goal['physical_equivalent_6m']}\n\n"
                f"추천 상품군 1순위: {products['products'][0]['name']} "
                f"({products['products'][0]['note']})\n\n"
                f"Risk Guard: {'✅ 통과' if risk_guard['passed'] else '⚠️ 위반 항목 있음'}\n"
                f"{products['disclaimer']}"
            )
        else:
            cf = cashflow or {}
            summary = (
                f"[은퇴 현금흐름 리포트]\n\n"
                f"생애단계: {profile['life_stage']} | 우선순위: {profile['priority']}\n\n"
                f"예상 월 수입: {cf.get('monthly_income', 0):,}원\n"
                f"예상 월 지출: {cf.get('monthly_expense', 0):,}원\n"
                f"월 부족분: {abs(cf.get('monthly_shortage', 0)):,}원 "
                f"({'부족' if cf.get('monthly_shortage', 0) < 0 else '충분'})\n"
                f"리스크 등급: {cf.get('risk_level', '미산출')}\n\n"
                f"추천 상품군 1순위: {products['products'][0]['name']} "
                f"({products['products'][0]['note']})\n\n"
                f"Risk Guard: {'✅ 통과' if risk_guard['passed'] else '⚠️ 위반 항목 있음'}\n"
                f"{products['disclaimer']}"
            )

        next_actions = (
            [
                "배달앱 주문을 이번 주 2회로 줄이기",
                "전북은행 ISA 계좌 개설 검토",
                "구독 서비스 1개 정리 (월 약 2~3만원)",
            ]
            if mode == "early_career"
            else [
                "연금 부족분 보완 상품 비교 시작",
                "보험료 부담률 점검 (월 소득 대비 10% 기준)",
                "JB금융 은퇴 설계 상담 예약",
            ]
        )

        return {
            "agent": "ReportAgent",
            "report_text": summary,
            "next_actions": next_actions,
            "risk_guard_passed": risk_guard["passed"],
        }


# ─── Orchestrator ─────────────────────────────────────────────────────────────

class WealthPathOrchestrator:
    """
    Multi-Agent Workflow Controller.
    Runs 7 agents sequentially, passing structured outputs between stages.

    Pipeline:
        ProfileAgent → SpendingAgent / CashflowAgent
        → GoalAgent → ProductAgent
        → RiskGuardAgent → ReportAgent
    """

    def __init__(self):
        self.profile_agent   = ProfileAgent()
        self.spending_agent  = SpendingAgent()
        self.cashflow_agent  = CashflowAgent()
        self.goal_agent      = GoalAgent()
        self.product_agent   = ProductAgent()
        self.risk_guard      = RiskGuardAgent()
        self.report_agent    = ReportAgent()

    def run(
        self,
        user: UserProfile,
        transactions: list[Transaction],
        target_amount: int = 10_000_000,
        monthly_medical: int = 250_000,
    ) -> dict:
        log = []

        # ── STAGE 1: JUDGE (Perceive) ─────────────────────────────────────
        profile  = self.profile_agent.run(user)
        log.append({"stage": 1, "agent": "ProfileAgent",  "status": "done"})

        spending = self.spending_agent.run(transactions, user.monthly_income)
        log.append({"stage": 1, "agent": "SpendingAgent", "status": "done"})

        cashflow = self.cashflow_agent.run(user, monthly_medical)
        log.append({"stage": 1, "agent": "CashflowAgent", "status": "done"})

        # ── STAGE 2: ACT ──────────────────────────────────────────────────
        goal     = self.goal_agent.run(user, spending, target_amount)
        log.append({"stage": 2, "agent": "GoalAgent",     "status": "done"})

        products = self.product_agent.run(profile)
        log.append({"stage": 2, "agent": "ProductAgent",  "status": "done"})

        # ── STAGE 3: VERIFY ───────────────────────────────────────────────
        risk     = self.risk_guard.run(
            all_results=[profile, spending, goal, products],
            explanation_text=goal.get("range_nudge", ""),
        )
        log.append({"stage": 3, "agent": "RiskGuardAgent","status": "done"})

        # ── FINAL: Report ─────────────────────────────────────────────────
        report   = self.report_agent.run(profile, spending, goal, products, risk, cashflow)
        log.append({"stage": 3, "agent": "ReportAgent",   "status": "done"})

        return {
            "execution_log":   log,
            "profile":         profile,
            "spending":        spending,
            "cashflow":        cashflow,
            "goal":            goal,
            "products":        products,
            "risk_guard":      risk,
            "report":          report,
        }
